[general]
import = [
   #"~/.config/alacritty/themes/themes/base16_default_dark.toml"
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]
[colors.primary]
#foreground = "#6a6a6b"
background = "#0f0f18"

[font]
size =10.5

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Light"

[window]
opacity = 1

[env]
  WINIT_X11_SCALE_FACTOR = "1"
  TERM = "xterm-256color"
